// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type Album struct {
	ID       int64  `json:"id"`
	Title    string `json:"title"`
	ArtistID *int64 `json:"artist_id"`
	Year     *int64 `json:"year"`
}

type Artist struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type Playlist struct {
	ID        int64      `json:"id"`
	Name      string     `json:"name"`
	CreatedAt *time.Time `json:"created_at"`
}

type PlaylistTrack struct {
	ID         int64 `json:"id"`
	PlaylistID int64 `json:"playlist_id"`
	TrackID    int64 `json:"track_id"`
	Position   int64 `json:"position"`
}

type Track struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	AlbumID     *int64 `json:"album_id"`
	ArtistID    *int64 `json:"artist_id"`
	TrackNumber *int64 `json:"track_number"`
	Duration    *int64 `json:"duration"`
	FilePath    string `json:"file_path"`
}
