// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"
)

const createAlbum = `-- name: CreateAlbum :one
INSERT INTO albums (title, artist_id, year) VALUES (?, ?, ?)
ON CONFLICT(title, artist_id) DO UPDATE SET title=excluded.title
RETURNING id, title, artist_id, year
`

type CreateAlbumParams struct {
	Title    string `json:"title"`
	ArtistID *int64 `json:"artist_id"`
	Year     *int64 `json:"year"`
}

func (q *Queries) CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error) {
	row := q.db.QueryRowContext(ctx, createAlbum, arg.Title, arg.ArtistID, arg.Year)
	var i Album
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ArtistID,
		&i.Year,
	)
	return i, err
}

const createArtist = `-- name: CreateArtist :one
INSERT INTO artists (name) VALUES (?)
ON CONFLICT(name) DO UPDATE SET name=excluded.name
RETURNING id, name
`

func (q *Queries) CreateArtist(ctx context.Context, name string) (Artist, error) {
	row := q.db.QueryRowContext(ctx, createArtist, name)
	var i Artist
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createTrack = `-- name: CreateTrack :one
INSERT INTO tracks (title, album_id, artist_id, track_number, duration, file_path) 
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(file_path) DO UPDATE SET 
    title=excluded.title, 
    album_id=excluded.album_id, 
    artist_id=excluded.artist_id, 
    track_number=excluded.track_number, 
    duration=excluded.duration
RETURNING id, title, album_id, artist_id, track_number, duration, file_path
`

type CreateTrackParams struct {
	Title       string `json:"title"`
	AlbumID     *int64 `json:"album_id"`
	ArtistID    *int64 `json:"artist_id"`
	TrackNumber *int64 `json:"track_number"`
	Duration    *int64 `json:"duration"`
	FilePath    string `json:"file_path"`
}

func (q *Queries) CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error) {
	row := q.db.QueryRowContext(ctx, createTrack,
		arg.Title,
		arg.AlbumID,
		arg.ArtistID,
		arg.TrackNumber,
		arg.Duration,
		arg.FilePath,
	)
	var i Track
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AlbumID,
		&i.ArtistID,
		&i.TrackNumber,
		&i.Duration,
		&i.FilePath,
	)
	return i, err
}

const listAlbums = `-- name: ListAlbums :many
SELECT id, title, artist_id, year FROM albums ORDER BY year DESC, title ASC
`

func (q *Queries) ListAlbums(ctx context.Context) ([]Album, error) {
	rows, err := q.db.QueryContext(ctx, listAlbums)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Album
	for rows.Next() {
		var i Album
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ArtistID,
			&i.Year,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listArtists = `-- name: ListArtists :many
SELECT id, name FROM artists ORDER BY name
`

func (q *Queries) ListArtists(ctx context.Context) ([]Artist, error) {
	rows, err := q.db.QueryContext(ctx, listArtists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Artist
	for rows.Next() {
		var i Artist
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTracks = `-- name: ListTracks :many
SELECT 
    tracks.id, tracks.title, tracks.album_id, tracks.artist_id, tracks.track_number, tracks.duration, tracks.file_path,
    COALESCE(artists.name, 'Unknown Artist') as artist_name,
    COALESCE(albums.title, 'Unknown Album') as album_title
FROM tracks 
LEFT JOIN artists ON tracks.artist_id = artists.id
LEFT JOIN albums ON tracks.album_id = albums.id
ORDER BY tracks.title
`

type ListTracksRow struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	AlbumID     *int64 `json:"album_id"`
	ArtistID    *int64 `json:"artist_id"`
	TrackNumber *int64 `json:"track_number"`
	Duration    *int64 `json:"duration"`
	FilePath    string `json:"file_path"`
	ArtistName  string `json:"artist_name"`
	AlbumTitle  string `json:"album_title"`
}

func (q *Queries) ListTracks(ctx context.Context) ([]ListTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, listTracks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTracksRow
	for rows.Next() {
		var i ListTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AlbumID,
			&i.ArtistID,
			&i.TrackNumber,
			&i.Duration,
			&i.FilePath,
			&i.ArtistName,
			&i.AlbumTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
