// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (Album, error)
	CreateArtist(ctx context.Context, name string) (Artist, error)
	CreateTrack(ctx context.Context, arg CreateTrackParams) (Track, error)
	ListAlbums(ctx context.Context) ([]Album, error)
	ListArtists(ctx context.Context) ([]Artist, error)
	ListTracks(ctx context.Context) ([]ListTracksRow, error)
}

var _ Querier = (*Queries)(nil)
